version: "3.1"

services:
  postgres:
    image: postgres:latest
    container_name: gostack-pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
    ports:
      - 5432:5432
